name: CI

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: wordpressmobile/android-build-image
    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: ./gradlew :plugin:check
